export enum InventoryObject {
    COIN = 'coin',
    TEQUILA= 'tequila',
    SUSPICIOUS_PACKET = 'suspicious packet',
    SAUSAGE = 'sausage',
    MOVIE_REVIEW = 'movie review',
    ICE_CREAM = 'ice cream',
    JUMPING_ROPE = 'jumping rope',
    A = 'A',
    B = 'B',
    C = 'C',
    D = 'D',
    E = 'E',
    F = 'F',
    G = 'G',
    H = 'H',
    I = 'I',
    J = 'J',
    K = 'K',
    L = 'L',
    M = 'M',
    N = 'N',
    O = 'O',
    P = 'P',
    Q = 'Q',
    R = 'R',
    S = 'S',
    T = 'T',
    U = 'U',
    V = 'V',
    W = 'W',
    X = 'X',
    Y = 'Y',
    Z = 'Z',
}

// This is the global inventory
export const INVENTORY: InventoryObject[] = [
    InventoryObject.COIN,
    InventoryObject.ICE_CREAM,
    InventoryObject.JUMPING_ROPE,
    InventoryObject.MOVIE_REVIEW,
    InventoryObject.A,
    InventoryObject.B,
    InventoryObject.C,
    InventoryObject.D,
    InventoryObject.E,
    InventoryObject.F,
    InventoryObject.G,
    /*InventoryObject.H,
    InventoryObject.I,
    InventoryObject.J,
    InventoryObject.K,
    InventoryObject.L,
    InventoryObject.M,
    InventoryObject.N,
    InventoryObject.O,
    InventoryObject.P,
    InventoryObject.Q,
    InventoryObject.R,
    InventoryObject.S,
    InventoryObject.T,
    InventoryObject.U,
    InventoryObject.V,
    InventoryObject.W,
    InventoryObject.X,
    InventoryObject.Y,
    InventoryObject.Z,*/
];

export function isInventoryObject(obj: any): obj is InventoryObject {
    return Object.values(InventoryObject).includes(obj);
}
